// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/booking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRequest) Reset() {
	*x = BookingRequest{}
	mi := &file_api_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRequest) ProtoMessage() {}

func (x *BookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRequest.ProtoReflect.Descriptor instead.
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *BookingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookingRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_api_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *BookingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BookingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*BookingResponse     `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingList) Reset() {
	*x = BookingList{}
	mi := &file_api_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingList) ProtoMessage() {}

func (x *BookingList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingList.ProtoReflect.Descriptor instead.
func (*BookingList) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *BookingList) GetBookings() []*BookingResponse {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{3}
}

var File_api_proto_booking_proto protoreflect.FileDescriptor

const file_api_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/booking.proto\x12\abooking\"8\n" +
	"\x0eBookingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"9\n" +
	"\x0fBookingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"C\n" +
	"\vBookingList\x124\n" +
	"\bbookings\x18\x01 \x03(\v2\x18.booking.BookingResponseR\bbookings\"\a\n" +
	"\x05Empty2\x8a\x01\n" +
	"\x0eBookingService\x12B\n" +
	"\rCreateBooking\x12\x17.booking.BookingRequest\x1a\x18.booking.BookingResponse\x124\n" +
	"\fListBookings\x12\x0e.booking.Empty\x1a\x14.booking.BookingListB\fZ\n" +
	"booking/pbb\x06proto3"

var (
	file_api_proto_booking_proto_rawDescOnce sync.Once
	file_api_proto_booking_proto_rawDescData []byte
)

func file_api_proto_booking_proto_rawDescGZIP() []byte {
	file_api_proto_booking_proto_rawDescOnce.Do(func() {
		file_api_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_booking_proto_rawDesc), len(file_api_proto_booking_proto_rawDesc)))
	})
	return file_api_proto_booking_proto_rawDescData
}

var file_api_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_booking_proto_goTypes = []any{
	(*BookingRequest)(nil),  // 0: booking.BookingRequest
	(*BookingResponse)(nil), // 1: booking.BookingResponse
	(*BookingList)(nil),     // 2: booking.BookingList
	(*Empty)(nil),           // 3: booking.Empty
}
var file_api_proto_booking_proto_depIdxs = []int32{
	1, // 0: booking.BookingList.bookings:type_name -> booking.BookingResponse
	0, // 1: booking.BookingService.CreateBooking:input_type -> booking.BookingRequest
	3, // 2: booking.BookingService.ListBookings:input_type -> booking.Empty
	1, // 3: booking.BookingService.CreateBooking:output_type -> booking.BookingResponse
	2, // 4: booking.BookingService.ListBookings:output_type -> booking.BookingList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_booking_proto_init() }
func file_api_proto_booking_proto_init() {
	if File_api_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_booking_proto_rawDesc), len(file_api_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_booking_proto_goTypes,
		DependencyIndexes: file_api_proto_booking_proto_depIdxs,
		MessageInfos:      file_api_proto_booking_proto_msgTypes,
	}.Build()
	File_api_proto_booking_proto = out.File
	file_api_proto_booking_proto_goTypes = nil
	file_api_proto_booking_proto_depIdxs = nil
}
